CREATE DATABASE IF NOT EXISTS data_mart;
USE data_mart;

create table DIM_GRUPPE (
	GRUPPE_ID BIGINT NOT NULL AUTO_INCREMENT,
	geburtsjahr INTEGER,
	familienstand VARCHAR(200),
	prioritaet VARCHAR(1),
	CONSTRAINT `pk_dim_gruppe` PRIMARY KEY(GRUPPE_ID)
);

create table DIM_REGION (
	REGION_ID BIGINT NOT NULL AUTO_INCREMENT,
	plz INTEGER,
	ort VARCHAR(200),
	CONSTRAINT `pk_dim_region` PRIMARY KEY(REGION_ID)
);

create table DIM_VERSICHERUNG (
	VERSICHERUNG_ID BIGINT NOT NULL AUTO_INCREMENT,
	versicherung_art VARCHAR(200),
	CONSTRAINT `pk_dim_versicherung` PRIMARY KEY(VERSICHERUNG_ID)
);

create table DIM_KUNDE (
	KUNDE_ID BIGINT NOT NULL AUTO_INCREMENT,
	kundennummer VARCHAR(200),
	CONSTRAINT `pk_dim_kunde` PRIMARY KEY(KUNDE_ID)
);

create table DIM_ZEIT (
	ZEIT_ID BIGINT NOT NULL AUTO_INCREMENT,
	jahr INTEGER,
	monat INTEGER,
	woche INTEGER,
	CONSTRAINT `pk_dim_zeit` PRIMARY KEY(ZEIT_ID)
);

create table FACT_AUSZAHLUNG_LV (
	ZEIT_ID BIGINT,
	GRUPPE_ID BIGINT,
	REGION_ID BIGINT,
	KUNDE_ID BIGINT, 
	auszahlung_betrag DECIMAL(12,2)
);

create table FACT_NEUWERT (
	ERSTZULASSUNG_ZEIT_ID BIGINT,
	GRUPPE_ID BIGINT,
	REGION_ID BIGINT,
	KUNDE_ID BIGINT,
	neuwert_betrag DECIMAL(12,2)
);

create table FACT_VERSICHERUNGEN (
	VERSICHERUNG_ID BIGINT,
	GRUPPE_ID BIGINT,
	REGION_ID BIGINT,
	versichert_anzahl INTEGER
);
