TRUNCATE DIM_GRUPPE;

TRUNCATE DIM_REGION;

TRUNCATE DIM_VERSICHERUNG;

TRUNCATE DIM_KUNDE;

TRUNCATE DIM_ZEIT;

TRUNCATE FACT_AUSZAHLUNG_LV;

TRUNCATE FACT_NEUWERT;

TRUNCATE FACT_VERSICHERUNGEN;