DROP DATABASE IF EXISTS integration_zone;
CREATE DATABASE integration_zone;
USE integration_zone;

CREATE TABLE STAMMDATEN_TRANSFORM (
	KuNr VARCHAR(6),
	Name VARCHAR(200),
	Vorname VARCHAR(200),
	Vorname2 VARCHAR(200),
	GebDatum DATE,
	GebOrt VARCHAR(200),
	Strasse VARCHAR(200),
	HausNr VARCHAR(200),
	PLZ VARCHAR(200),
	Ort VARCHAR(200),
	TelPrivat VARCHAR(200),
	TelArbeit VARCHAR(200),
	TelMobil VARCHAR(200),
	Fax VARCHAR(200),
	Email1 VARCHAR(200),
	Email2 VARCHAR(200),
	Prio VARCHAR(1),
	FamStand VARCHAR(200),
	AnzKinder INTEGER,
	AnzKinderMV INTEGER,
	EhepartnerMV VARCHAR(1)
);

CREATE TABLE LV_TRANSFORM (
	VNr VARCHAR(8),
	KuNr VARCHAR(6),
	Wertfaktor DECIMAL(3,2),
	Vbeginn DATE,
	Laufzeit VARCHAR(200),
	Monatsrate DECIMAL(12,2),
	Quartalsrate DECIMAL(12,2),
	Halbjahresrate DECIMAL(12,2),
	Jahresrate DECIMAL(12,2),
	Beguenstigter VARCHAR(2),
	BU VARCHAR(1),
	Zahlungsweise VARCHAR(1)
);

CREATE TABLE KV_TRANSFORM (
	VNr VARCHAR(7),
	KuNr VARCHAR(6),
	Art VARCHAR(200),
	VBeginn DATE,
	Rate  DECIMAL(12,2),
	SB  DECIMAL(12,2),
	R1  DECIMAL(12,2),
	R2  DECIMAL(12,2),
	R3  DECIMAL(12,2)
);

CREATE TABLE KFZ_TRANSFORM (
	VNr VARCHAR(8),
	KuNr VARCHAR(6),
	KFZ_KZ VARCHAR(9),
	Art VARCHAR(1),
	Neuwert DECIMAL(12,2),
	Erstzulassung DATE,
	VBeginn DATE,
	HP_Monat DECIMAL(12,2),
	TK_Monat DECIMAL(12,2),
	VK_Monat DECIMAL(12,2),
	HPSatz INTEGER,
	TKSatz INTEGER,
	VKSatz INTEGER,
	SB_TK DECIMAL(12,2),
	SB_VK DECIMAL(12,2),
	VK VARCHAR(1),
	Schadenssumme_Sach DECIMAL(12,2),
	Schadenssumme_Person DECIMAL(12,2)
);

CREATE TABLE SACH_TRANSFORM (
	VNr VARCHAR(8),
	KuNr VARCHAR(6),
	Art VARCHAR(3),
	VWert DECIMAL(12,2),
	VBeginn DATE,
	Laufzeit INTEGER,
	K_Frist INTEGER,
	Rate_Monat DECIMAL(12,2),
	Rate_Quartal DECIMAL(12,2),
	Rate_Halbjahr DECIMAL(12,2),
	Rate_Jahr DECIMAL(12,2),
	Zahlungsweise VARCHAR(1)
);

CREATE TABLE BU_TRANSFORM (
	VNr VARCHAR(8),
	KuNr VARCHAR(6),
	Wertbetrag DECIMAL(12,2),
	Rate_Monat DECIMAL(12,2),
	Rate_Quartal DECIMAL(12,2),
	Rate_Halbjahr DECIMAL(12,2),
	Rate_Jahr DECIMAL(12,2),
	Zahlungsweise VARCHAR(200)
);

CREATE TABLE STAMMDATEN_ERROR (
	KuNr VARCHAR(200),
	Name VARCHAR(200),
	Vorname VARCHAR(200),
	Vorname2 VARCHAR(200),
	GebDatum VARCHAR(200),
	GebOrt VARCHAR(200),
	Strasse VARCHAR(200),
	HausNr VARCHAR(200),
	PLZ VARCHAR(200),
	Ort VARCHAR(200),
	TelPrivat VARCHAR(200),
	TelArbeit VARCHAR(200),
	TelMobil VARCHAR(200),
	Fax VARCHAR(200),
	Email1 VARCHAR(200),
	Email2 VARCHAR(200),
	Prio VARCHAR(200),
	FamStand VARCHAR(200),
	AnzKinder VARCHAR(200),
	AnzKinderMV VARCHAR(200),
	EhepartnerMV VARCHAR(200)
);

CREATE TABLE LV_ERROR (
	VNr VARCHAR(200),
	KuNr VARCHAR(200),
	Wertfaktor VARCHAR(200),
	Vbeginn VARCHAR(200),
	Laufzeit VARCHAR(200),
	Rate_Monat VARCHAR(200),
	Rate_Halbjahr VARCHAR(200),
	Rate_Jahr VARCHAR(200),
	Beguenstigter VARCHAR(200),
	BU VARCHAR(200),
	Zahlungsweise VARCHAR(200)
);

CREATE TABLE KV_ERROR (
	VNr VARCHAR(200),
	KuNr VARCHAR(200),
	Art VARCHAR(200),
	VBeginn VARCHAR(200),
	Rate VARCHAR(200),
	SB VARCHAR(200),
	R1 VARCHAR(200),
	R2 VARCHAR(200),
	R3 VARCHAR(200)
);

CREATE TABLE KFZ_ERROR (
	VNr VARCHAR(200),
	KuNr VARCHAR(200),
	KFZ_KZ VARCHAR(200),
	Art VARCHAR(200),
	Neuwert VARCHAR(200),
	Erstzulassung VARCHAR(200),
	VBeginn VARCHAR(200),
	HP_Monat VARCHAR(200),
	TK_Monat VARCHAR(200),
	VK_Monat VARCHAR(200),
	HPSatz VARCHAR(200),
	TKSatz VARCHAR(200),
	VKSatz VARCHAR(200),
	SB_TK VARCHAR(200),
	SB_VK VARCHAR(200),
	VK VARCHAR(200),
	Schadenssumme_Sach VARCHAR(200),
	Schadenssumme_Person VARCHAR(200)
);

CREATE TABLE SACH_ERROR (
	VNr VARCHAR(200),
	KuNr VARCHAR(200),
	Art VARCHAR(200),
	VWert VARCHAR(200),
	VBeginn VARCHAR(200),
	Laufzeit VARCHAR(200),
	K_Frist VARCHAR(200),
	Rate_Monat VARCHAR(200),
	Rate_Quartal VARCHAR(200),
	Rate_Halbjahr VARCHAR(200),
	Rate_Jahr VARCHAR(200),
	Zahlungsweise VARCHAR(200)
);

CREATE TABLE BU_ERROR (
	VNr VARCHAR(200),
	KuNr VARCHAR(200),
	Wertbetrag VARCHAR(200),
	Rate_Monat VARCHAR(200),
	Rate_Quartal VARCHAR(200),
	Rate_Halbjahr VARCHAR(200),
	Rate_Jahr VARCHAR(200),
	Zahlungsweise VARCHAR(200)
);

CREATE TABLE METADATA (
	Import_Table VARCHAR(200),
	Integration_Time DATETIME
);
