DROP DATABASE IF EXISTS integration_zone;
CREATE DATABASE integration_zone;
USE integration_zone;

CREATE TABLE STAMMDATEN_TRANSFORM (
	KuNr VARCHAR(6) NOT NULL PRIMARY KEY,
	Name VARCHAR(200) NOT NULL,
	Vorname VARCHAR(200) NOT NULL,
	Vorname2 VARCHAR(200),
	GebDatum DATE NOT NULL,
	GebOrt VARCHAR(200) NOT NULL,
	Strasse VARCHAR(200) NOT NULL,
	HausNr VARCHAR(200) NOT NULL,
	PLZ VARCHAR(200) NOT NULL,
	Ort VARCHAR(200) NOT NULL,
	TelPrivat VARCHAR(200),
	TelArbeit VARCHAR(200),
	TelMobil VARCHAR(200),
	Fax VARCHAR(200),
	Email1 VARCHAR(200) NOT NULL,
	Email2 VARCHAR(200),
	Prio VARCHAR(1) NOT NULL,
	FamStand VARCHAR(200) NOT NULL,
	AnzKinder INTEGER,
	AnzKinderMV INTEGER,
	EhepartnerMV BOOLEAN
);

CREATE TABLE LV_TRANSFORM (
	VNr VARCHAR(8) NOT NULL PRIMARY KEY,
	KuNr VARCHAR(6) NOT NULL,
	Wertfaktor DECIMAL(3,2) NOT NULL,
	Vbeginn DATE NOT NULL,
	Laufzeit VARCHAR(200) NOT NULL,
	Monatsrate DECIMAL(12,2) NOT NULL,
	Quartalsrate DECIMAL(12,2) NOT NULL,
	Halbjahresrate DECIMAL(12,2) NOT NULL,
	Jahresrate DECIMAL(12,2) NOT NULL,
	Beguenstigter VARCHAR(2) NOT NULL,
	BU VARCHAR(1) NOT NULL,
	Zahlungsweise VARCHAR(1) NOT NULL
);

CREATE TABLE KV_TRANSFORM (
	VNr VARCHAR(7) NOT NULL PRIMARY KEY,
	KuNr VARCHAR(6) NOT NULL,
	Art VARCHAR(200) NOT NULL,
	VBeginn DATE NOT NULL,
	Rate  DECIMAL(12,2) NOT NULL,
	SB  DECIMAL(12,2),
	R1  DECIMAL(12,2) NOT NULL,
	R2  DECIMAL(12,2) NOT NULL,
	R3  DECIMAL(12,2) NOT NULL
);

CREATE TABLE KFZ_TRANSFORM (
	VNr VARCHAR(8) NOT NULL PRIMARY KEY,
	KuNr VARCHAR(6) NOT NULL,
	KFZ_KZ VARCHAR(9) NOT NULL,
	Art VARCHAR(1) NOT NULL,
	Neuwert DECIMAL(12,2) NOT NULL,
	Erstzulassung DATE NOT NULL,
	VBeginn DATE NOT NULL,
	HP_Monat DECIMAL(12,2) NOT NULL,
	TK_Monat DECIMAL(12,2) NOT NULL,
	VK_Monat DECIMAL(12,2) NOT NULL,
	HPSatz INTEGER NOT NULL,
	TKSatz INTEGER NOT NULL,
	VKSatz INTEGER NOT NULL,
	SB_TK DECIMAL(12,2),
	SB_VK DECIMAL(12,2),
	VK VARCHAR(1) NOT NULL,
	Schadenssumme_Sach DECIMAL(12,2) NOT NULL,
	Schadenssumme_Person DECIMAL(12,2) NOT NULL
);

CREATE TABLE SACH_TRANSFORM (
	VNr VARCHAR(8) NOT NULL PRIMARY KEY,
	KuNr VARCHAR(6) NOT NULL,
	Art VARCHAR(3) NOT NULL,
	VWert DECIMAL(12,2) NOT NULL,
	VBeginn DATE NOT NULL,
	Laufzeit INTEGER NOT NULL,
	K_Frist INTEGER NOT NULL,
	Rate_Monat DECIMAL(12,2) NOT NULL,
	Rate_Quartal DECIMAL(12,2) NOT NULL,
	Rate_Halbjahr DECIMAL(12,2) NOT NULL,
	Rate_Jahr DECIMAL(12,2) NOT NULL,
	Zahlungsweise VARCHAR(1) NOT NULL
);

CREATE TABLE BU_TRANSFORM (
	VNr VARCHAR(8) NOT NULL PRIMARY KEY,
	KuNr VARCHAR(6) NOT NULL,
	Wertbetrag DECIMAL(12,2) NOT NULL,
	Rate_Monat DECIMAL(12,2) NOT NULL,
	Rate_Quartal DECIMAL(12,2) NOT NULL,
	Rate_Halbjahr DECIMAL(12,2) NOT NULL,
	Rate_Jahr DECIMAL(12,2) NOT NULL,
	Zahlungsweise VARCHAR(1) NOT NULL
);

CREATE TABLE STAMMDATEN_ERROR (
	KuNr VARCHAR(200),
	Name VARCHAR(200),
	Vorname VARCHAR(200),
	Vorname2 VARCHAR(200),
	GebDatum VARCHAR(200),
	GebOrt VARCHAR(200),
	Strasse VARCHAR(200),
	HausNr VARCHAR(200),
	PLZ VARCHAR(200),
	Ort VARCHAR(200),
	TelPrivat VARCHAR(200),
	TelArbeit VARCHAR(200),
	TelMobil VARCHAR(200),
	Fax VARCHAR(200),
	Email1 VARCHAR(200),
	Email2 VARCHAR(200),
	Prio VARCHAR(200),
	FamStand VARCHAR(200),
	AnzKinder VARCHAR(200),
	AnzKinderMV VARCHAR(200),
	EhepartnerMV VARCHAR(200)
);

CREATE TABLE LV_ERROR (
	VNr VARCHAR(200),
	KuNr VARCHAR(200),
	Wertfaktor VARCHAR(200),
	Vbeginn VARCHAR(200),
	Laufzeit VARCHAR(200),
	Monatsrate VARCHAR(200),
	Quartalsrate VARCHAR(200),
	Halbjahresrate VARCHAR(200),
	Jahresrate VARCHAR(200),
	Beguenstigter VARCHAR(200),
	BU VARCHAR(200),
	Zahlungsweise VARCHAR(200)
);

CREATE TABLE KV_ERROR (
	VNr VARCHAR(200),
	KuNr VARCHAR(200),
	Art VARCHAR(200),
	VBeginn VARCHAR(200),
	Rate VARCHAR(200),
	SB VARCHAR(200),
	R1 VARCHAR(200),
	R2 VARCHAR(200),
	R3 VARCHAR(200)
);

CREATE TABLE KFZ_ERROR (
	VNr VARCHAR(200),
	KuNr VARCHAR(200),
	KFZ_KZ VARCHAR(200),
	Art VARCHAR(200),
	Neuwert VARCHAR(200),
	Erstzulassung VARCHAR(200),
	VBeginn VARCHAR(200),
	HP_Monat VARCHAR(200),
	TK_Monat VARCHAR(200),
	VK_Monat VARCHAR(200),
	HPSatz VARCHAR(200),
	TKSatz VARCHAR(200),
	VKSatz VARCHAR(200),
	SB_TK VARCHAR(200),
	SB_VK VARCHAR(200),
	VK VARCHAR(200),
	Schadenssumme_Sach VARCHAR(200),
	Schadenssumme_Person VARCHAR(200)
);

CREATE TABLE SACH_ERROR (
	VNr VARCHAR(200),
	KuNr VARCHAR(200),
	Art VARCHAR(200),
	VWert VARCHAR(200),
	VBeginn VARCHAR(200),
	Laufzeit VARCHAR(200),
	K_Frist VARCHAR(200),
	Rate_Monat VARCHAR(200),
	Rate_Quartal VARCHAR(200),
	Rate_Halbjahr VARCHAR(200),
	Rate_Jahr VARCHAR(200),
	Zahlungsweise VARCHAR(200)
);

CREATE TABLE BU_ERROR (
	VNr VARCHAR(200),
	KuNr VARCHAR(200),
	Wertbetrag VARCHAR(200),
	Rate_Monat VARCHAR(200),
	Rate_Quartal VARCHAR(200),
	Rate_Halbjahr VARCHAR(200),
	Rate_Jahr VARCHAR(200),
	Zahlungsweise VARCHAR(200)
);